language: node_js
node_js:
- node

script: echo "CI is running......"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test

services:
  - postgresql

before_script:
  - psql -c 'create database politico_db;' -U postgres
  - psql -c "create user politico with PASSWORD 'niyobobo';" -U postgres
  - npm run database