language: node_js
node_js:
- node

script: echo "CI is running......"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - node ./server/database/connection createTables