language: node_js
node_js:
- node

script: echo "CI is running......"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --forceExit --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage